# Generated by Django 4.2.7 on 2025-08-04 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deposit',
            new_name='recycling_d_user_id_40fe95_idx',
            old_name='recycling_d_user_id_b8a5a1_idx',
        ),
        migrations.RenameIndex(
            model_name='deposit',
            new_name='recycling_d_machine_e52581_idx',
            old_name='recycling_d_machine_2c8b5f_idx',
        ),
        migrations.RenameIndex(
            model_name='deposit',
            new_name='recycling_d_materia_602e86_idx',
            old_name='recycling_d_materia_4c5e8a_idx',
        ),
    ]
